In [1]:
import pandas as pd
import io
from sqlalchemy import create_engine

In [2]:
engine = create_engine("postgresql://postgres:postgres@localhost:5433/ny_taxi")

In [3]:
engine.connect()

In [15]:
df_tier = pd.read_csv('green_tripdata_2019-10.csv', iterator=True, chunksize=10000)

In [16]:
df = next(df_tier)

In [17]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2019-10-01 00:26:02,2019-10-01 00:39:58,N,1,112,196,1,5.88,18.0,0.50,0.5,0.00,0.0,NaN,0.3,19.30,2,1,0.0
1,1,2019-10-01 00:18:11,2019-10-01 00:22:38,N,1,43,263,1,0.80,5.0,3.25,0.5,0.00,0.0,NaN,0.3,9.05,2,1,0.0
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1,255,228,2,7.50,21.5,0.50,0.5,0.00,0.0,NaN,0.3,22.80,2,1,0.0
3,1,2019-10-01 00:37:40,2019-10-01 00:41:49,N,1,181,181,1,0.90,5.5,0.50,0.5,0.00,0.0,NaN,0.3,6.80,2,1,0.0
4,2,2019-10-01 00:08:13,2019-10-01 00:17:56,N,1,97,188,1,2.52,10.0,0.50,0.5,2.26,0.0,NaN,0.3,13.56,1,1,0.0

In [18]:
df.dtypes

VendorID                   int64
lpep_pickup_datetime      object
lpep_dropoff_datetime     object
store_and_fwd_flag        object
RatecodeID                 int64
PULocationID               int64
DOLocationID               int64
passenger_count            int64
trip_distance            float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
ehail_fee                float64
improvement_surcharge    float64
total_amount             float64
payment_type               int64
trip_type                  int64
congestion_surcharge     float64
dtype: object

In [19]:
df['lpep_pickup_datetime'] = pd.to_datetime(df['lpep_pickup_datetime'])
df['lpep_dropoff_datetime'] = pd.to_datetime(df['lpep_dropoff_datetime'])

In [20]:
df.dtypes

VendorID                          int64
lpep_pickup_datetime     datetime64[ns]
lpep_dropoff_datetime    datetime64[ns]
store_and_fwd_flag               object
RatecodeID                        int64
PULocationID                      int64
DOLocationID                      int64
passenger_count                   int64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                      int64
trip_type                         int64
congestion_surcharge            float64
dtype: object

In [21]:
df.head(n=0).to_sql(name="green_taxi_data", con=engine, if_exists="replace")

0

In [22]:
count = 0

df_tier = pd.read_csv('green_tripdata_2019-10.csv', iterator=True, chunksize=10000)

for tier in df_tier:
    df = tier
    df.to_sql(name="green_taxi_data", con=engine, if_exists="append")

    count+=1
    print(f"Insert chunk {count}")

Insert chunk 1
Insert chunk 2
Insert chunk 3
Insert chunk 4
Insert chunk 5
Insert chunk 6
Insert chunk 7
Insert chunk 8
Insert chunk 9
Insert chunk 10
Insert chunk 11
Insert chunk 12
Insert chunk 13
Insert chunk 14
Insert chunk 15
Insert chunk 16
Insert chunk 17
Insert chunk 18
Insert chunk 19
Insert chunk 20
Insert chunk 21
Insert chunk 22
Insert chunk 23
Insert chunk 24
Insert chunk 25
Insert chunk 26
Insert chunk 27
Insert chunk 28
Insert chunk 29
Insert chunk 30
Insert chunk 31
Insert chunk 32
Insert chunk 33
Insert chunk 34
Insert chunk 35
Insert chunk 36
Insert chunk 37
Insert chunk 38
Insert chunk 39
Insert chunk 40
Insert chunk 41
Insert chunk 42
Insert chunk 43
Insert chunk 44
Insert chunk 45
Insert chunk 46
Insert chunk 47
Insert chunk 48

In [35]:
zone_df = pd.read_csv("taxi_zone_lookup.csv")

In [42]:
zone_df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [43]:
zone_df.count()

LocationID      265
Borough         265
Zone            264
service_zone    263
dtype: int64

In [44]:
zone_df.to_sql(name="taxi_zone_look_up", con=engine, if_exists="replace")

265